### ISSUE TITLE
Coworking spaces?

### ISSUE THREAD

**Issue by danse** [sic2/awesome-sicily#11]
Who comes to a place to work on technology usually needs a coworking space or a cafe with fast internet, i think we should add the section here. I only know Vulcanic in Catania and the Impact Hub in Syracuse. We should link to a website, as one usually wants to check the prices before choosing

**Comment by sic2** [comment]
They are already in the list: https://github.com/sic2/awesome-sicily#incubatori-acceleratori-e-hubs

Do you think we should move them to a separate sublist?

**Comment by sic2** [comment]
Oh, just saw the PR. Will continue the discussion there

**Comment by danse** [comment]
Hum, you are right. Well these are rather different things. Usually an individual is not admitted to an incubator or accelerator, if not within a company accepted by that program. Coworking spaces accept anybody who pays a daily rate

**Comment by danse** [comment]
In Sicily these things probably often overlap ...
